### ISSUE TITLE
wkhtml issues

### ISSUE THREAD

**Issue by TheGroundZero** [xtiankisutsa/achari#1]
The two wkhtml need to have execute permission for the current user to be able to be called by your tool

    chmod u+x tools/wkhtml*

Also, I think there's a syntax issue preventing the tool from working properly

    ./achari.sh --pdf /home/[full-path-to-folder-with-KeepNote]
      ___       _                _ 
     / _ \     | |              (_)
    / /_\ \ ___| |__   __ _ _ __ _ 
    |  _  |/ __| '_ \ / _` | '__| |
    | | | | (__| | | | (_| | |  | |
    \_| |_/\___|_| |_|\__,_|_|  |_|   
                                                                                                  
    Version: 0.1.0 beta
    Developed by: Christian Kisutsa
    
    ===================
     Converting to PDF 
    ===================
    [-]Enter PDF title:
    PDF Title
    
    [-]Enter PDF file name: (without whitespace and .pdf)
    PDF_Title
    
    [-]Setting up environment...
    
    [-]Listing files to convert...
    [full-path-to-folder-with-KeepNote]/0) general/page.html
    [full-path-to-folder-with-KeepNote]/0) notes/page.html
    [...]
    
    [-]Listing images to convert...
    
    [-]Dumping file locations...
    
    [-]Processing 19 files....
     
    [-]Generating shrinked PDF
    -s specified in incorrect location
    
    Name:
      wkhtmltopdf 0.12.4 (with patched qt)
    
    Synopsis:
      wkhtmltopdf [GLOBAL OPTION]... [OBJECT]... <output file>
      
    Document objects:
      wkhtmltopdf is able to put several objects into the output file, an object is
      either a single webpage, a cover webpage or a table of content.  The objects
      are put into the output document in the order they are specified on the
      command line, options can be specified on a per object basis or in the global
      options area. Options from the Global Options section can only be placed in
      the global options area
    
    [ ... ]
    
    Contact:
      If you experience bugs or want to request new features please visit 
      <https://github.com/wkhtmltopdf/wkhtmltopdf/issues>
    
     
    [-]Generating regular PDF
    -s specified in incorrect location
    
    [... Again full --help info from wkhtmltopdf ...]
    
    
    [-]Cleaning up..
    mv: cannot stat 'tools/PDF_Title_small.pdf': No such file or directory
    mv: cannot stat 'tools/PDF_Title_large.pdf': No such file or directory

**Comment by xtiankisutsa** [comment]
I have ran a test on my end and the tool seems to be working perfectly fine. The two binaries in the tools folder definitely need to be executable. I will update the wiki to highlight this. 

If the full path to the specific keep note folder has been provided correctly, then i believe that probably the notes themselves are not named in numerical order.  

I wrote a [blog](http://www.shadowinfosec.io/2017/02/achari-converting-keepnotes-to-pdf-and.html) post that highlights how the notes should be formatted in terms of the page names, so that achari can convert them sequentially, in numerical order.

**Comment by TheGroundZero** [comment]
The wkhtml kept complaining about the location of the "-s" or "--page-size" parameter. I moved it to the beginning and now it's no longer complaining.
Another reason for the issue could also have been that I included a space in the document title, since the $pdf_title var wasn't enclosed in quotes

**Comment by xtiankisutsa** [comment]
Thanks for spotting that. I have accepted your pull request. Thanks again for trying out the tool and giving your feedback, it's much appreciated.
